version: '3.4'

services:
  php:
    build:
      context: ./docker/php
    networks:
      - pgnet
    volumes:
      - ./app:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini

  nginx:
    image: nginx:latest
    networks:
      - pgnet
    ports:
      - 8081:80
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d

  postgres:
    container_name: "pgmaster"
    image: postgres:13.3
    networks:
      - pgnet
    environment:
      POSTGRES_DB: admin
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
    ports:
      - 5435:5432
    volumes:
      - ./volumes/pgmaster/:/var/lib/postgresql/data
      - my-vol:/var/lib/postgresql/data

  redis:
    container_name: "redis"
    image: redis:7.2.3
    networks:
      - pgnet
    ports:
      - 6380:6379

volumes:
  my-vol:
networks:
  pgnet:
